import discord

RANKS = [
    # NEGATIVKARMA (Höllenpfad)
    (-144000, "Höllenfürst der Zehn Zungen des Zorns", "🔥", discord.Colour.dark_red()),
    (-141000, "Großinquisitor des Widerspruchs", "🩸", discord.Colour.red()),
    (-138000, "Dunkler Statthalter der Verdammten", "🕷️", discord.Colour.dark_grey()),
    (-135000, "Erzverführer im Palast des Sitra Achra", "👹", discord.Colour.dark_magenta()),
    (-132000, "Flammenzunge von Gamchab", "🔥", discord.Colour.orange()),
    (-129000, "Saturnalischer Dominus der Qliphoth", "🪓", discord.Colour.dark_orange()),
    (-126000, "Fürst der sieben Pestkessel", "☠️", discord.Colour.dark_teal()),
    (-123000, "Blutrichter der Verderbten", "🩸", discord.Colour.dark_red()),
    (-120000, "Legat des inneren Abgrunds", "🕳️", discord.Colour.dark_grey()),
    (-117000, "Kardinal der Fäulnis", "🦠", discord.Colour.dark_green()),
    (-114000, "Erzadept des zerschlagenen Lichts", "💀", discord.Colour.dark_grey()),
    (-111000, "Verwesungsprophet von Harab Serapel", "🦴", discord.Colour.dark_grey()),
    (-108000, "Apostel des Schmerzes", "🩸", discord.Colour.red()),
    (-105000, "Schattenherr der Finsternispforte", "🌑", discord.Colour.dark_blue()),
    (-102000, "Peiniger der verdorrten Essenz", "🪦", discord.Colour.dark_grey()),
    (-99000, "Totengeist der leeren Sphären", "👻", discord.Colour.greyple()),
    (-96000, "Verlorener Baumeister der Zersetzung", "🧟", discord.Colour.dark_green()),
    (-93000, "Rufer aus Thaumiel", "📯", discord.Colour.dark_purple()),
    (-90000, "Zersplitterter Hohepriester der Lüge", "🪞", discord.Colour.dark_grey()),
    (-87000, "Teuflischer Tribun der Dämonischen Konklave", "😈", discord.Colour.red()),
    (-84000, "Besessener des vergessenen Kodex", "📜", discord.Colour.dark_gold()),
    (-81000, "Schwarzer Wächter des blutenden Baumes", "🌳", discord.Colour.dark_green()),
    (-78000, "Ordensmeister der Schattenloge", "🕸️", discord.Colour.dark_grey()),
    (-75000, "Zerstörer der inneren Pforte", "🗝️", discord.Colour.dark_grey()),
    (-72000, "Erzdämon des verdunkelten Thrones", "👺", discord.Colour.dark_red()),
    (-69000, "Hüter des endlosen Zwielichts", "🌒", discord.Colour.dark_blue()),
    (-66000, "Prophet des Chaosseins", "🌀", discord.Colour.dark_teal()),
    (-63000, "Hochkanzler des brennenden Schweigens", "🤫", discord.Colour.dark_grey()),
    (-60000, "Verderber der formenden Flamme", "🔥", discord.Colour.orange()),
    (-57000, "Verfluchter Alchemist der Gegenexistenz", "⚗️", discord.Colour.dark_gold()),
    (-54000, "Dunkler Jünger der Gebrochenen Schriftrolle", "📖", discord.Colour.dark_grey()),
    (-51000, "Hexenmeister des leeren Siegels", "🔮", discord.Colour.purple()),
    (-48000, "Verzehrer der reinen Namen", "🦷", discord.Colour.dark_grey()),
    (-45000, "Schattenwanderer von Golachab", "🌑", discord.Colour.dark_blue()),
    (-42000, "Priester der entarteten Sephiroth", "🕎", discord.Colour.dark_gold()),
    (-39000, "Seelenfresser aus Thagirion", "🦴", discord.Colour.dark_grey()),
    (-36000, "Geheimbundskanzler der Fäulnisordnung", "🦠", discord.Colour.dark_green()),
    (-33000, "Hüter des zerbrochenen Siegels", "🔓", discord.Colour.dark_grey()),
    (-30000, "Legionär der dunklen Triade", "⚔️", discord.Colour.dark_grey()),
    (-27000, "Verborgener Prophet der Vergessenheit", "🕳️", discord.Colour.dark_grey()),
    (-24000, "Lehrmeister der Täuschung", "🦊", discord.Colour.orange()),
    (-21000, "Niederschreiber der Schattenchroniken", "📓", discord.Colour.dark_grey()),
    (-18000, "Bewahrer der sieben Flüche", "🧿", discord.Colour.dark_blue()),
    (-15000, "Nachtwächter der Umkehrung", "🌒", discord.Colour.dark_blue()),
    (-12000, "Schüler des entweihten Pfades", "🛤️", discord.Colour.dark_grey()),
    (-9000, "Suchender des gefallenen Lichts", "🔦", discord.Colour.dark_grey()),
    (-6000, "Träger der karmischen Schuld", "⚖️", discord.Colour.dark_grey()),
    (-3000, "Umherirrender Geist", "👻", discord.Colour.greyple()),
    (-1000, "Gebrochene Seele", "💔", discord.Colour.dark_grey()),
    (-1, "Schwankender zwischen Schatten", "🌫️", discord.Colour.dark_grey()),
    (0, "Suchender des Äquilibriums im Tempel des Einen", "⚖️", discord.Colour.lighter_grey()),
    # POSITIVKARMA (Sephirothischer Aufstieg)
    (1, "Erwachender Geist", "✨", discord.Colour.teal()),
    (3000, "Schüler des inneren Lichts", "🌱", discord.Colour.green()),
    (6000, "Bote der Reinheit", "🕊️", discord.Colour.blue()),
    (9000, "Suchender im Garten von Malkuth", "🌳", discord.Colour.green()),
    (12000, "Adept der fließenden Ströme", "💧", discord.Colour.blue()),
    (15000, "Hüter der Stille", "🤍", discord.Colour.lighter_grey()),
    (18000, "Bewahrer des Geheimnisses von Yesod", "🌙", discord.Colour.purple()),
    (21000, "Lichtwanderer der unteren Pfade", "🌄", discord.Colour.gold()),
    (24000, "Schüler des göttlichen Gleichgewichts", "⚖️", discord.Colour.lighter_grey()),
    (27000, "Sanftmütiger der Wahrheit", "🕯️", discord.Colour.gold()),
    (30000, "Priester des goldenen Netzach", "🌟", discord.Colour.gold()),
    (33000, "Gesandter der Harmonie", "🎶", discord.Colour.teal()),
    (36000, "Chorführer des Tiphereth", "🎼", discord.Colour.gold()),
    (39000, "Weiser des aufblühenden Baumes", "🌳", discord.Colour.green()),
    (42000, "Gesalbter des Lichts", "💡", discord.Colour.yellow()),
    (45000, "Wächter des himmlischen Kodex", "📜", discord.Colour.gold()),
    (48000, "Archivar des heiligen Pfades", "📚", discord.Colour.gold()),
    (51000, "Prophet der sieben Siegel", "🔯", discord.Colour.gold()),
    (54000, "Ritter der verborgenen Rose", "🌹", discord.Colour.red()),
    (57000, "Diener des Lichttempels", "🏛️", discord.Colour.gold()),
    (60000, "Kanonikus des Ein-Sof", "🔆", discord.Colour.gold()),
    (63000, "Erzadept von Hod", "🧙", discord.Colour.purple()),
    (66000, "Großpriester des silbernen Throns", "🪙", discord.Colour.lighter_grey()),
    (69000, "Leuchtender Ordensmeister von Geburah", "🛡️", discord.Colour.gold()),
    (72000, "Bannerträger der göttlichen Ordnung", "🚩", discord.Colour.gold()),
    (75000, "Geweihter der Einheit", "🤲", discord.Colour.gold()),
    (78000, "Hoher Vater des Sephiroth-Bundes", "👑", discord.Colour.gold()),
    (81000, "Lichtkanzler der Krone von Binah", "👑", discord.Colour.gold()),
    (84000, "Engel der Weisheit", "🦢", discord.Colour.lighter_grey()),
    (87000, "Seraphischer Wächter von Chokmah", "🕊️", discord.Colour.lighter_grey()),
    (90000, "Erwählter von Kether", "🌞", discord.Colour.gold()),
    (93000, "Weiser des höchsten Pfades", "🧙‍♂️", discord.Colour.gold()),
    (96000, "Erzengelischer Verwalter der Lichttore", "🕍", discord.Colour.gold()),
    (99000, "Mittler der reinen Sephiroth", "🕊️", discord.Colour.lighter_grey()),
    (102000, "Heiliger Vorsteher des Weltenbaumes", "🌳", discord.Colour.green()),
    (105000, "Erzmagus der goldenen Harmonie", "🧙‍♂️", discord.Colour.gold()),
    (108000, "Paladin der göttlichen Stimme", "⚔️", discord.Colour.gold()),
    (111000, "Herr der sieben Lichter", "🌈", discord.Colour.lighter_grey()),
    (114000, "Sonnenfürst der Urordnung", "🌞", discord.Colour.gold()),
    (117000, "Seraph von Ein Sof", "👼", discord.Colour.lighter_grey()),
    (120000, "Wächter der letzten Pforte", "🚪", discord.Colour.gold()),
    (123000, "Himmlischer General des kosmischen Siegels", "🔱", discord.Colour.gold()),
    (126000, "Großarchivar des Lichttempels", "📚", discord.Colour.gold()),
    (129000, "Erlöster Hüter der göttlichen Matrix", "🧬", discord.Colour.gold()),
    (132000, "Messianischer Träger des ewigen Bundes", "🕊️", discord.Colour.lighter_grey()),
    (135000, "Hoher Seraph der himmlischen Ordnung", "👼", discord.Colour.lighter_grey()),
    (138000, "Lichtmanifest des göttlichen Willens", "✨", discord.Colour.gold()),
    (141000, "Stellvertreter des Schöpfers", "👑", discord.Colour.gold()),
    (144000, "Großarchitekt des Lichts aller Welten", "🌟", discord.Colour.gold()),
]
